// Generated by https://quicktype.io

export interface CheckTokenResponse {
  sub:           string;
  idColaborador: number;
  roles:         string[];
  iat:           number;
  exp:           number;
}
